[
 {
   "id": 1,
   "building_id": 1,
   "employee_id": 1,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "8/30/2014",
   "date_of_inspection": "3/16/2017",
   "inspection_certificate": "Certified",
   "information": "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
   "notes": "in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",
   "created_at": "11/19/1985",
   "updated_at": "9/3/2008"
 },
 {
   "id": 2,
   "building_id": 2,
   "employee_id": 2,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "11/10/1986",
   "date_of_inspection": "5/7/1999",
   "inspection_certificate": "Certified",
   "information": "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
   "notes": "eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",
   "created_at": "6/4/1982",
   "updated_at": "9/30/2000"
 },
 {
   "id": 3,
   "building_id": 3,
   "employee_id": 3,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "9/14/1979",
   "date_of_inspection": "8/29/1977",
   "inspection_certificate": "Certified",
   "information": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.",
   "notes": "proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus",
   "created_at": "11/25/2012",
   "updated_at": "4/20/2001"
 },
 {
   "id": 4,
   "building_id": 4,
   "employee_id": 4,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "6/1/1980",
   "date_of_inspection": "3/11/1980",
   "inspection_certificate": "Not Certified",
   "information": "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
   "notes": "vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat",
   "created_at": "10/2/1999",
   "updated_at": "3/9/1989"
 },
 {
   "id": 5,
   "building_id": 5,
   "employee_id": 5,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "5/18/1999",
   "date_of_inspection": "2/3/1978",
   "inspection_certificate": "Not Certified",
   "information": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
   "notes": "ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu",
   "created_at": "8/8/1997",
   "updated_at": "1/13/2018"
 },
 {
   "id": 6,
   "building_id": 6,
   "employee_id": 6,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "4/25/2011",
   "date_of_inspection": "4/26/2005",
   "inspection_certificate": "Certified",
   "information": "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
   "notes": "nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit",
   "created_at": "3/17/2006",
   "updated_at": "10/21/2004"
 },
 {
   "id": 7,
   "building_id": 7,
   "employee_id": 7,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "1/19/2013",
   "date_of_inspection": "1/11/1999",
   "inspection_certificate": "Certified",
   "information": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.",
   "notes": "sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at",
   "created_at": "3/26/2007",
   "updated_at": "8/26/1993"
 },
 {
   "id": 8,
   "building_id": 8,
   "employee_id": 8,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "12/27/2015",
   "date_of_inspection": "6/12/1997",
   "inspection_certificate": "Certified",
   "information": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
   "notes": "cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus",
   "created_at": "2/20/1976",
   "updated_at": "10/20/1975"
 },
 {
   "id": 9,
   "building_id": 9,
   "employee_id": 9,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "6/5/2014",
   "date_of_inspection": "4/2/1983",
   "inspection_certificate": "Certified",
   "information": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
   "notes": "faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi",
   "created_at": "8/14/2013",
   "updated_at": "9/12/2007"
 },
 {
   "id": 10,
   "building_id": 10,
   "employee_id": 10,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "10/25/2000",
   "date_of_inspection": "6/7/1993",
   "inspection_certificate": "Certified",
   "information": "Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
   "notes": "vel est donec odio justo sollicitudin ut suscipit a feugiat et eros",
   "created_at": "6/26/2004",
   "updated_at": "1/5/1980"
 },
 {
   "id": 11,
   "building_id": 11,
   "employee_id": 11,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "8/22/1999",
   "date_of_inspection": "12/6/1977",
   "inspection_certificate": "Certified",
   "information": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
   "notes": "donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst",
   "created_at": "9/11/2007",
   "updated_at": "9/16/1995"
 },
 {
   "id": 12,
   "building_id": 12,
   "employee_id": 12,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "10/15/2017",
   "date_of_inspection": "2/26/1997",
   "inspection_certificate": "Not Certified",
   "information": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
   "notes": "quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt",
   "created_at": "5/6/1991",
   "updated_at": "1/22/1988"
 },
 {
   "id": 13,
   "building_id": 13,
   "employee_id": 13,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "7/24/2018",
   "date_of_inspection": "6/26/2017",
   "inspection_certificate": "Not Certified",
   "information": "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.",
   "notes": "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra",
   "created_at": "10/5/2013",
   "updated_at": "6/8/2017"
 },
 {
   "id": 14,
   "building_id": 14,
   "employee_id": 14,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "10/1/1990",
   "date_of_inspection": "12/28/1989",
   "inspection_certificate": "Certified",
   "information": "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
   "notes": "ut odio cras mi pede malesuada in imperdiet et commodo",
   "created_at": "11/6/1976",
   "updated_at": "12/24/2003"
 },
 {
   "id": 15,
   "building_id": 15,
   "employee_id": 15,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "3/5/1980",
   "date_of_inspection": "4/9/1979",
   "inspection_certificate": "Certified",
   "information": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.",
   "notes": "lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique",
   "created_at": "5/16/1997",
   "updated_at": "4/27/2003"
 },
 {
   "id": 16,
   "building_id": 16,
   "employee_id": 16,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "6/7/2003",
   "date_of_inspection": "8/26/2010",
   "inspection_certificate": "Not Certified",
   "information": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
   "notes": "vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id",
   "created_at": "7/19/1995",
   "updated_at": "9/3/1999"
 },
 {
   "id": 17,
   "building_id": 17,
   "employee_id": 17,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "12/9/1983",
   "date_of_inspection": "2/13/1996",
   "inspection_certificate": "Certified",
   "information": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
   "notes": "condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar",
   "created_at": "12/29/1976",
   "updated_at": "7/29/1995"
 },
 {
   "id": 18,
   "building_id": 18,
   "employee_id": 18,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "1/31/1987",
   "date_of_inspection": "4/25/2019",
   "inspection_certificate": "Certified",
   "information": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
   "notes": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan",
   "created_at": "4/2/2004",
   "updated_at": "5/29/2016"
 },
 {
   "id": 19,
   "building_id": 19,
   "employee_id": 19,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "12/28/1980",
   "date_of_inspection": "3/21/1980",
   "inspection_certificate": "Not Certified",
   "information": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
   "notes": "iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate",
   "created_at": "12/23/2004",
   "updated_at": "7/26/1976"
 },
 {
   "id": 20,
   "building_id": 20,
   "employee_id": 20,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "6/1/2002",
   "date_of_inspection": "10/4/2010",
   "inspection_certificate": "Certified",
   "information": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
   "notes": "justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus",
   "created_at": "1/16/2011",
   "updated_at": "11/9/1979"
 },
 {
   "id": 21,
   "building_id": 21,
   "employee_id": 21,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "3/2/1988",
   "date_of_inspection": "8/27/1978",
   "inspection_certificate": "Certified",
   "information": "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
   "notes": "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio",
   "created_at": "6/15/1976",
   "updated_at": "7/22/1997"
 },
 {
   "id": 22,
   "building_id": 22,
   "employee_id": 22,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "12/9/2018",
   "date_of_inspection": "2/5/2002",
   "inspection_certificate": "Not Certified",
   "information": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.",
   "notes": "imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi",
   "created_at": "3/12/2011",
   "updated_at": "6/26/1986"
 },
 {
   "id": 23,
   "building_id": 23,
   "employee_id": 23,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "8/7/1982",
   "date_of_inspection": "8/28/1990",
   "inspection_certificate": "Not Certified",
   "information": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
   "notes": "viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a",
   "created_at": "6/9/1987",
   "updated_at": "9/10/2017"
 },
 {
   "id": 24,
   "building_id": 24,
   "employee_id": 24,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "7/25/1977",
   "date_of_inspection": "11/24/2005",
   "inspection_certificate": "Certified",
   "information": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
   "notes": "faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam",
   "created_at": "7/15/2011",
   "updated_at": "10/14/1990"
 },
 {
   "id": 25,
   "building_id": 25,
   "employee_id": 25,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "7/31/1981",
   "date_of_inspection": "3/29/1982",
   "inspection_certificate": "Not Certified",
   "information": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
   "notes": "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
   "created_at": "9/15/1998",
   "updated_at": "2/28/1987"
 },
 {
   "id": 26,
   "building_id": 26,
   "employee_id": 26,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "1/15/2014",
   "date_of_inspection": "5/22/2016",
   "inspection_certificate": "Not Certified",
   "information": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
   "notes": "in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam",
   "created_at": "1/1/2013",
   "updated_at": "7/21/2005"
 },
 {
   "id": 27,
   "building_id": 27,
   "employee_id": 27,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "7/30/1983",
   "date_of_inspection": "9/19/1985",
   "inspection_certificate": "Certified",
   "information": "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
   "notes": "quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero",
   "created_at": "8/20/2014",
   "updated_at": "4/26/1994"
 },
 {
   "id": 28,
   "building_id": 28,
   "employee_id": 28,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "9/11/1978",
   "date_of_inspection": "2/26/1982",
   "inspection_certificate": "Not Certified",
   "information": "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
   "notes": "pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in",
   "created_at": "12/17/2008",
   "updated_at": "10/26/1997"
 },
 {
   "id": 29,
   "building_id": 29,
   "employee_id": 29,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "11/2/2014",
   "date_of_inspection": "5/22/2005",
   "inspection_certificate": "Not Certified",
   "information": "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
   "notes": "amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus",
   "created_at": "7/22/2017",
   "updated_at": "6/27/1995"
 },
 {
   "id": 30,
   "building_id": 30,
   "employee_id": 30,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "12/11/2018",
   "date_of_inspection": "1/2/1982",
   "inspection_certificate": "Not Certified",
   "information": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
   "notes": "elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in",
   "created_at": "11/14/1978",
   "updated_at": "11/16/1976"
 },
 {
   "id": 31,
   "building_id": 31,
   "employee_id": 31,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "11/6/2014",
   "date_of_inspection": "3/27/2003",
   "inspection_certificate": "Certified",
   "information": "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
   "notes": "eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare",
   "created_at": "6/13/2019",
   "updated_at": "12/17/1987"
 },
 {
   "id": 32,
   "building_id": 32,
   "employee_id": 32,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "4/24/1986",
   "date_of_inspection": "1/18/1995",
   "inspection_certificate": "Certified",
   "information": "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
   "notes": "sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis",
   "created_at": "2/9/1999",
   "updated_at": "10/15/1994"
 },
 {
   "id": 33,
   "building_id": 33,
   "employee_id": 33,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "8/11/2013",
   "date_of_inspection": "7/15/1976",
   "inspection_certificate": "Not Certified",
   "information": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.",
   "notes": "morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in",
   "created_at": "6/21/1988",
   "updated_at": "3/31/1981"
 },
 {
   "id": 34,
   "building_id": 34,
   "employee_id": 34,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "8/28/2006",
   "date_of_inspection": "10/3/2006",
   "inspection_certificate": "Not Certified",
   "information": "Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
   "notes": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui",
   "created_at": "3/7/2009",
   "updated_at": "12/12/2000"
 },
 {
   "id": 35,
   "building_id": 35,
   "employee_id": 35,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "8/7/1983",
   "date_of_inspection": "6/8/2004",
   "inspection_certificate": "Not Certified",
   "information": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
   "notes": "magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
   "created_at": "3/4/1992",
   "updated_at": "12/11/2016"
 },
 {
   "id": 36,
   "building_id": 36,
   "employee_id": 36,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "4/12/1994",
   "date_of_inspection": "2/12/1980",
   "inspection_certificate": "Not Certified",
   "information": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
   "notes": "quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet",
   "created_at": "7/31/2016",
   "updated_at": "11/22/1978"
 },
 {
   "id": 37,
   "building_id": 37,
   "employee_id": 37,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "11/27/1998",
   "date_of_inspection": "9/28/1996",
   "inspection_certificate": "Certified",
   "information": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
   "notes": "libero convallis eget eleifend luctus ultricies eu nibh quisque id",
   "created_at": "10/11/2002",
   "updated_at": "1/29/2010"
 },
 {
   "id": 38,
   "building_id": 38,
   "employee_id": 38,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "6/4/2019",
   "date_of_inspection": "7/9/1979",
   "inspection_certificate": "Certified",
   "information": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
   "notes": "sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus",
   "created_at": "6/3/1994",
   "updated_at": "3/4/1977"
 },
 {
   "id": 39,
   "building_id": 39,
   "employee_id": 39,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "9/17/1980",
   "date_of_inspection": "10/2/1998",
   "inspection_certificate": "Certified",
   "information": "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
   "notes": "ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus",
   "created_at": "8/14/2014",
   "updated_at": "3/30/1990"
 },
 {
   "id": 40,
   "building_id": 40,
   "employee_id": 40,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "1/25/1988",
   "date_of_inspection": "1/29/1988",
   "inspection_certificate": "Certified",
   "information": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.",
   "notes": "nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor",
   "created_at": "6/22/2011",
   "updated_at": "7/20/2014"
 },
 {
   "id": 41,
   "building_id": 41,
   "employee_id": 41,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "10/10/2005",
   "date_of_inspection": "9/24/2010",
   "inspection_certificate": "Not Certified",
   "information": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
   "notes": "nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",
   "created_at": "12/6/2002",
   "updated_at": "12/2/1988"
 },
 {
   "id": 42,
   "building_id": 42,
   "employee_id": 42,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "12/27/1999",
   "date_of_inspection": "10/22/1996",
   "inspection_certificate": "Certified",
   "information": "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
   "notes": "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices",
   "created_at": "8/16/1991",
   "updated_at": "5/5/1999"
 },
 {
   "id": 43,
   "building_id": 43,
   "employee_id": 43,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "5/13/1994",
   "date_of_inspection": "3/17/2016",
   "inspection_certificate": "Not Certified",
   "information": "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",
   "notes": "molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",
   "created_at": "1/25/2002",
   "updated_at": "11/12/2010"
 },
 {
   "id": 44,
   "building_id": 44,
   "employee_id": 44,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "9/17/2013",
   "date_of_inspection": "7/23/2010",
   "inspection_certificate": "Not Certified",
   "information": "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
   "notes": "orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin",
   "created_at": "9/15/2014",
   "updated_at": "11/23/1989"
 },
 {
   "id": 45,
   "building_id": 45,
   "employee_id": 45,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "9/28/1990",
   "date_of_inspection": "5/30/1983",
   "inspection_certificate": "Not Certified",
   "information": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
   "notes": "velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",
   "created_at": "3/30/2003",
   "updated_at": "9/2/2018"
 },
 {
   "id": 46,
   "building_id": 46,
   "employee_id": 46,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "11/30/2018",
   "date_of_inspection": "4/5/2005",
   "inspection_certificate": "Certified",
   "information": "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.",
   "notes": "magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes",
   "created_at": "8/4/2011",
   "updated_at": "8/11/2000"
 },
 {
   "id": 47,
   "building_id": 47,
   "employee_id": 47,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "7/29/1999",
   "date_of_inspection": "5/30/2004",
   "inspection_certificate": "Certified",
   "information": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
   "notes": "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero",
   "created_at": "3/8/2007",
   "updated_at": "9/21/1986"
 },
 {
   "id": 48,
   "building_id": 48,
   "employee_id": 48,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "6/29/1992",
   "date_of_inspection": "9/8/1979",
   "inspection_certificate": "Certified",
   "information": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
   "notes": "id nisl venenatis lacinia aenean sit amet justo morbi ut odio",
   "created_at": "5/1/1977",
   "updated_at": "1/16/1985"
 },
 {
   "id": 49,
   "building_id": 49,
   "employee_id": 49,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "3/13/1990",
   "date_of_inspection": "3/25/1998",
   "inspection_certificate": "Certified",
   "information": "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
   "notes": "eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes",
   "created_at": "2/11/1993",
   "updated_at": "1/22/1977"
 },
 {
   "id": 50,
   "building_id": 50,
   "employee_id": 50,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "8/23/2004",
   "date_of_inspection": "11/24/1988",
   "inspection_certificate": "Certified",
   "information": "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
   "notes": "eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis",
   "created_at": "6/30/1978",
   "updated_at": "7/27/1994"
 },
 {
   "id": 51,
   "building_id": 51,
   "employee_id": 51,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "3/12/2013",
   "date_of_inspection": "1/11/2018",
   "inspection_certificate": "Certified",
   "information": "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
   "notes": "lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce",
   "created_at": "8/28/2012",
   "updated_at": "5/23/1992"
 },
 {
   "id": 52,
   "building_id": 52,
   "employee_id": 52,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "11/9/1977",
   "date_of_inspection": "9/22/1984",
   "inspection_certificate": "Not Certified",
   "information": "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
   "notes": "vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna",
   "created_at": "9/17/1976",
   "updated_at": "4/14/1996"
 },
 {
   "id": 53,
   "building_id": 53,
   "employee_id": 53,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "6/20/2016",
   "date_of_inspection": "6/25/1989",
   "inspection_certificate": "Not Certified",
   "information": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
   "notes": "in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes",
   "created_at": "4/6/2013",
   "updated_at": "5/5/2004"
 },
 {
   "id": 54,
   "building_id": 54,
   "employee_id": 54,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "7/2/1981",
   "date_of_inspection": "7/13/2004",
   "inspection_certificate": "Certified",
   "information": "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
   "notes": "non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum",
   "created_at": "5/4/1990",
   "updated_at": "10/24/2011"
 },
 {
   "id": 55,
   "building_id": 55,
   "employee_id": 55,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "3/19/2004",
   "date_of_inspection": "8/12/2009",
   "inspection_certificate": "Certified",
   "information": "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
   "notes": "libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in",
   "created_at": "11/9/1997",
   "updated_at": "1/7/1984"
 },
 {
   "id": 56,
   "building_id": 56,
   "employee_id": 56,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "8/27/1996",
   "date_of_inspection": "1/19/1996",
   "inspection_certificate": "Not Certified",
   "information": "Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.",
   "notes": "cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur",
   "created_at": "4/22/2002",
   "updated_at": "5/22/1982"
 },
 {
   "id": 57,
   "building_id": 57,
   "employee_id": 57,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "8/30/1981",
   "date_of_inspection": "9/19/2017",
   "inspection_certificate": "Certified",
   "information": "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
   "notes": "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit",
   "created_at": "6/7/2018",
   "updated_at": "4/20/2004"
 },
 {
   "id": 58,
   "building_id": 58,
   "employee_id": 58,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "7/30/2010",
   "date_of_inspection": "9/18/1991",
   "inspection_certificate": "Certified",
   "information": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.",
   "notes": "sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam",
   "created_at": "12/7/2012",
   "updated_at": "10/14/2012"
 },
 {
   "id": 59,
   "building_id": 59,
   "employee_id": 59,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "2/17/1980",
   "date_of_inspection": "1/31/1976",
   "inspection_certificate": "Certified",
   "information": "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
   "notes": "nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac",
   "created_at": "10/26/1990",
   "updated_at": "3/27/2018"
 },
 {
   "id": 60,
   "building_id": 60,
   "employee_id": 60,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "4/26/2013",
   "date_of_inspection": "3/16/1979",
   "inspection_certificate": "Certified",
   "information": "Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
   "notes": "pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices",
   "created_at": "2/16/1979",
   "updated_at": "12/15/2004"
 },
 {
   "id": 61,
   "building_id": 61,
   "employee_id": 61,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "7/12/1976",
   "date_of_inspection": "6/8/2003",
   "inspection_certificate": "Not Certified",
   "information": "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
   "notes": "at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in",
   "created_at": "6/1/2001",
   "updated_at": "6/11/1998"
 },
 {
   "id": 62,
   "building_id": 62,
   "employee_id": 62,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "5/3/1978",
   "date_of_inspection": "3/9/2007",
   "inspection_certificate": "Certified",
   "information": "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
   "notes": "nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
   "created_at": "9/10/1987",
   "updated_at": "12/20/2002"
 },
 {
   "id": 63,
   "building_id": 63,
   "employee_id": 63,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "12/27/2006",
   "date_of_inspection": "10/15/2000",
   "inspection_certificate": "Certified",
   "information": "Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.",
   "notes": "semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante",
   "created_at": "5/1/1977",
   "updated_at": "10/25/2013"
 },
 {
   "id": 64,
   "building_id": 64,
   "employee_id": 64,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "2/7/1979",
   "date_of_inspection": "2/16/1978",
   "inspection_certificate": "Certified",
   "information": "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
   "notes": "condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu",
   "created_at": "4/22/1999",
   "updated_at": "7/14/1987"
 },
 {
   "id": 65,
   "building_id": 65,
   "employee_id": 65,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "9/18/2018",
   "date_of_inspection": "11/27/1993",
   "inspection_certificate": "Certified",
   "information": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
   "notes": "platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",
   "created_at": "4/29/1990",
   "updated_at": "6/21/2002"
 },
 {
   "id": 66,
   "building_id": 66,
   "employee_id": 66,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "8/30/1977",
   "date_of_inspection": "3/5/2016",
   "inspection_certificate": "Certified",
   "information": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
   "notes": "mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel",
   "created_at": "1/1/1981",
   "updated_at": "5/16/1993"
 },
 {
   "id": 67,
   "building_id": 67,
   "employee_id": 67,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "5/19/1981",
   "date_of_inspection": "11/23/2005",
   "inspection_certificate": "Not Certified",
   "information": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
   "notes": "natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",
   "created_at": "5/2/2009",
   "updated_at": "2/16/1978"
 },
 {
   "id": 68,
   "building_id": 68,
   "employee_id": 68,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "2/21/2006",
   "date_of_inspection": "1/20/2018",
   "inspection_certificate": "Not Certified",
   "information": "Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.",
   "notes": "ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at",
   "created_at": "3/3/1984",
   "updated_at": "12/15/1986"
 },
 {
   "id": 69,
   "building_id": 69,
   "employee_id": 69,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "7/26/1990",
   "date_of_inspection": "2/2/2007",
   "inspection_certificate": "Certified",
   "information": "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
   "notes": "donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue",
   "created_at": "7/8/1997",
   "updated_at": "7/2/1989"
 },
 {
   "id": 70,
   "building_id": 70,
   "employee_id": 70,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "11/6/1995",
   "date_of_inspection": "1/5/1980",
   "inspection_certificate": "Certified",
   "information": "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
   "notes": "rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam",
   "created_at": "7/6/1977",
   "updated_at": "8/13/1976"
 },
 {
   "id": 71,
   "building_id": 71,
   "employee_id": 71,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "12/5/1988",
   "date_of_inspection": "9/19/1994",
   "inspection_certificate": "Not Certified",
   "information": "Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
   "notes": "suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id",
   "created_at": "6/22/1992",
   "updated_at": "10/27/2009"
 },
 {
   "id": 72,
   "building_id": 72,
   "employee_id": 72,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "12/13/1975",
   "date_of_inspection": "9/19/1990",
   "inspection_certificate": "Certified",
   "information": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
   "notes": "id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in",
   "created_at": "9/15/1984",
   "updated_at": "11/15/2012"
 },
 {
   "id": 73,
   "building_id": 73,
   "employee_id": 73,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "5/25/2004",
   "date_of_inspection": "5/10/1992",
   "inspection_certificate": "Not Certified",
   "information": "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.",
   "notes": "purus phasellus in felis donec semper sapien a libero nam dui proin leo",
   "created_at": "10/4/2013",
   "updated_at": "3/18/2017"
 },
 {
   "id": 74,
   "building_id": 74,
   "employee_id": 74,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "4/15/2015",
   "date_of_inspection": "5/1/1998",
   "inspection_certificate": "Not Certified",
   "information": "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
   "notes": "nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",
   "created_at": "4/1/2001",
   "updated_at": "3/3/1999"
 },
 {
   "id": 75,
   "building_id": 75,
   "employee_id": 75,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "12/6/1999",
   "date_of_inspection": "10/22/1996",
   "inspection_certificate": "Certified",
   "information": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
   "notes": "egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies",
   "created_at": "1/27/2001",
   "updated_at": "7/23/2016"
 },
 {
   "id": 76,
   "building_id": 76,
   "employee_id": 76,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "5/13/2019",
   "date_of_inspection": "2/15/2019",
   "inspection_certificate": "Not Certified",
   "information": "Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
   "notes": "rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo",
   "created_at": "6/1/2018",
   "updated_at": "8/11/2015"
 },
 {
   "id": 77,
   "building_id": 77,
   "employee_id": 77,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "12/24/1983",
   "date_of_inspection": "8/4/2001",
   "inspection_certificate": "Not Certified",
   "information": "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
   "notes": "et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida",
   "created_at": "1/28/2016",
   "updated_at": "12/26/2013"
 },
 {
   "id": 78,
   "building_id": 78,
   "employee_id": 78,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "2/9/1997",
   "date_of_inspection": "4/25/1992",
   "inspection_certificate": "Not Certified",
   "information": "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.",
   "notes": "potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus",
   "created_at": "11/1/1985",
   "updated_at": "4/26/1978"
 },
 {
   "id": 79,
   "building_id": 79,
   "employee_id": 79,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "10/12/1996",
   "date_of_inspection": "10/8/1991",
   "inspection_certificate": "Certified",
   "information": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
   "notes": "luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",
   "created_at": "11/6/2010",
   "updated_at": "10/19/2013"
 },
 {
   "id": 80,
   "building_id": 80,
   "employee_id": 80,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "10/10/1987",
   "date_of_inspection": "10/1/1999",
   "inspection_certificate": "Certified",
   "information": "Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",
   "notes": "augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis",
   "created_at": "5/2/1982",
   "updated_at": "12/12/2004"
 },
 {
   "id": 81,
   "building_id": 81,
   "employee_id": 81,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "9/15/1998",
   "date_of_inspection": "4/12/1986",
   "inspection_certificate": "Not Certified",
   "information": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
   "notes": "sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam",
   "created_at": "9/2/1982",
   "updated_at": "3/11/1992"
 },
 {
   "id": 82,
   "building_id": 82,
   "employee_id": 82,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "4/28/1987",
   "date_of_inspection": "6/11/2011",
   "inspection_certificate": "Not Certified",
   "information": "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.",
   "notes": "aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed",
   "created_at": "9/6/1980",
   "updated_at": "12/5/1991"
 },
 {
   "id": 83,
   "building_id": 83,
   "employee_id": 83,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "12/5/1996",
   "date_of_inspection": "8/16/2016",
   "inspection_certificate": "Not Certified",
   "information": "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
   "notes": "turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
   "created_at": "7/7/1990",
   "updated_at": "5/11/2012"
 },
 {
   "id": 84,
   "building_id": 84,
   "employee_id": 84,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "2/8/2013",
   "date_of_inspection": "9/24/2017",
   "inspection_certificate": "Certified",
   "information": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
   "notes": "tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam",
   "created_at": "4/20/1987",
   "updated_at": "10/6/1977"
 },
 {
   "id": 85,
   "building_id": 85,
   "employee_id": 85,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "5/29/1986",
   "date_of_inspection": "4/29/2004",
   "inspection_certificate": "Not Certified",
   "information": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
   "notes": "ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl",
   "created_at": "10/22/2012",
   "updated_at": "8/18/2004"
 },
 {
   "id": 86,
   "building_id": 86,
   "employee_id": 86,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "8/9/1986",
   "date_of_inspection": "12/3/1976",
   "inspection_certificate": "Not Certified",
   "information": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
   "notes": "a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
   "created_at": "7/7/1982",
   "updated_at": "9/20/1990"
 },
 {
   "id": 87,
   "building_id": 87,
   "employee_id": 87,
   "building_type": "Commercial",
   "status": "Inactive",
   "date_of_installation": "11/16/2013",
   "date_of_inspection": "12/23/1985",
   "inspection_certificate": "Not Certified",
   "information": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
   "notes": "mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa",
   "created_at": "5/23/2000",
   "updated_at": "2/9/2014"
 },
 {
   "id": 88,
   "building_id": 88,
   "employee_id": 88,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "1/21/1981",
   "date_of_inspection": "2/9/2006",
   "inspection_certificate": "Certified",
   "information": "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
   "notes": "erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi",
   "created_at": "3/10/1993",
   "updated_at": "3/5/1989"
 },
 {
   "id": 89,
   "building_id": 89,
   "employee_id": 89,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "12/24/2012",
   "date_of_inspection": "7/18/1981",
   "inspection_certificate": "Not Certified",
   "information": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
   "notes": "faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut",
   "created_at": "3/29/1998",
   "updated_at": "6/3/2010"
 },
 {
   "id": 90,
   "building_id": 90,
   "employee_id": 90,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "5/31/1980",
   "date_of_inspection": "4/9/2014",
   "inspection_certificate": "Certified",
   "information": "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
   "notes": "turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis",
   "created_at": "2/2/2018",
   "updated_at": "9/25/1991"
 },
 {
   "id": 91,
   "building_id": 91,
   "employee_id": 91,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "2/7/2002",
   "date_of_inspection": "3/13/2003",
   "inspection_certificate": "Not Certified",
   "information": "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
   "notes": "lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia",
   "created_at": "11/24/2013",
   "updated_at": "12/17/2010"
 },
 {
   "id": 92,
   "building_id": 92,
   "employee_id": 92,
   "building_type": "Corporate",
   "status": "Active",
   "date_of_installation": "8/18/1981",
   "date_of_inspection": "12/20/2017",
   "inspection_certificate": "Not Certified",
   "information": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
   "notes": "mi sit amet lobortis sapien sapien non mi integer ac",
   "created_at": "3/25/2018",
   "updated_at": "4/5/2010"
 },
 {
   "id": 93,
   "building_id": 93,
   "employee_id": 93,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "4/1/2005",
   "date_of_inspection": "4/14/2012",
   "inspection_certificate": "Not Certified",
   "information": "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
   "notes": "diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere",
   "created_at": "8/11/2019",
   "updated_at": "4/26/2019"
 },
 {
   "id": 94,
   "building_id": 94,
   "employee_id": 94,
   "building_type": "Hybrid",
   "status": "Inactive",
   "date_of_installation": "6/16/1991",
   "date_of_inspection": "12/22/2014",
   "inspection_certificate": "Not Certified",
   "information": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
   "notes": "maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo",
   "created_at": "10/14/2015",
   "updated_at": "8/14/2012"
 },
 {
   "id": 95,
   "building_id": 95,
   "employee_id": 95,
   "building_type": "Residential",
   "status": "Inactive",
   "date_of_installation": "6/17/1990",
   "date_of_inspection": "1/17/2017",
   "inspection_certificate": "Certified",
   "information": "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
   "notes": "posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis",
   "created_at": "12/10/1997",
   "updated_at": "11/23/2003"
 },
 {
   "id": 96,
   "building_id": 96,
   "employee_id": 96,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "7/19/2017",
   "date_of_inspection": "1/10/2006",
   "inspection_certificate": "Certified",
   "information": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
   "notes": "quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet",
   "created_at": "3/25/1988",
   "updated_at": "4/25/2018"
 },
 {
   "id": 97,
   "building_id": 97,
   "employee_id": 97,
   "building_type": "Residential",
   "status": "Active",
   "date_of_installation": "6/9/1979",
   "date_of_inspection": "4/2/2010",
   "inspection_certificate": "Not Certified",
   "information": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.",
   "notes": "dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse",
   "created_at": "4/30/1994",
   "updated_at": "4/19/1983"
 },
 {
   "id": 98,
   "building_id": 98,
   "employee_id": 98,
   "building_type": "Corporate",
   "status": "Inactive",
   "date_of_installation": "9/28/2019",
   "date_of_inspection": "2/29/1976",
   "inspection_certificate": "Not Certified",
   "information": "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
   "notes": "erat fermentum justo nec condimentum neque sapien placerat ante nulla",
   "created_at": "7/3/1994",
   "updated_at": "6/5/1976"
 },
 {
   "id": 99,
   "building_id": 99,
   "employee_id": 99,
   "building_type": "Hybrid",
   "status": "Active",
   "date_of_installation": "7/20/1994",
   "date_of_inspection": "11/30/1991",
   "inspection_certificate": "Not Certified",
   "information": "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
   "notes": "porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi",
   "created_at": "9/10/2018",
   "updated_at": "5/14/1988"
 },
 {
   "id": 100,
   "building_id": 100,
   "employee_id": 100,
   "building_type": "Commercial",
   "status": "Active",
   "date_of_installation": "7/27/1981",
   "date_of_inspection": "12/27/2004",
   "inspection_certificate": "Certified",
   "information": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
   "notes": "arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget",
   "created_at": "5/3/1988",
   "updated_at": "9/26/1977"
 }
]