[
    [
        "https://cdn.worldvectorlogo.com/logos/iata-1.svg",
        "iata"
    ],[
        "https://cdn.worldvectorlogo.com/logos/emmis-communications.svg",
        "ammis"
    ],[
        "https://cdn.worldvectorlogo.com/logos/hunkemoller.svg",
        "hunkmoller"
    ],[
        "https://cdn.worldvectorlogo.com/logos/klm-4.svg",
        "kim"
    ],[
        "https://cdn.worldvectorlogo.com/logos/boiron-27692.svg",
        "boiron"
    ],[
        "https://cdn.worldvectorlogo.com/logos/au-la-plata-buenos-aires.svg",
        "alpba"
    ],[
        "https://cdn.worldvectorlogo.com/logos/designer-shoe-warehouse.svg",
        "dsw"
    ],[
        "https://cdn.worldvectorlogo.com/logos/advanta.svg",
        "advanta"
    ],[
        "https://cdn.worldvectorlogo.com/logos/salling-bank.svg",
        "salling"
    ],[
        "https://cdn.worldvectorlogo.com/logos/buick-5.svg",
        "buick"
    ],[
        "https://cdn.worldvectorlogo.com/logos/sensient.svg",
        "sansient"
    ],[
        "https://cdn.worldvectorlogo.com/logos/decibel-first.svg",
        "decbel"
    ]
]